#!/usr/bin/env python3
"""Refresh the scan-dependent sections of oeis/README.md from local data.

    python3 oeis_readme.py                  # fresh/ -> oeis/README.md
    python3 oeis_readme.py --results myrun  # another completed run

The published comparison uses the committed oeis/*.txt snapshots. Refresh
those separately with check_oeis.py --refresh when OEIS itself changes.
"""

import argparse
from pathlib import Path
import subprocess
import sys

import check_oeis
import oeis_audit


ROOT = Path(__file__).resolve().parent
README = ROOT / "oeis" / "README.md"
PROGRESS_END = "## Compute cost"
COVERED_END = "### In a covered family, but not computable here"


def published(stem):
    path = ROOT / "oeis" / f"{stem}.txt"
    if not path.is_file():
        raise ValueError(f"missing published snapshot: {path}")
    terms = check_oeis.read_terms(path)
    if not terms:
        raise ValueError(f"empty published snapshot: {path}")
    return terms


def scan(directory):
    frontiers = check_oeis.frontiers(directory)
    kinds = ("gap", "lonely", "aloof", "equidistant", "pairwise")
    if any(not frontiers.get(kind) for kind in kinds):
        raise ValueError(f"{directory}/frontier.txt needs all five frontiers")
    rows = {kind: check_oeis.rows(directory, kind)
            for kind in (*kinds, "balanced")}
    for kind in kinds:
        if not rows[kind]:
            raise ValueError(f"missing {kind} records in {directory}")
        if rows[kind][-1][1] > frontiers[kind]:
            raise ValueError(f"{kind} last record exceeds its frontier")
    return frontiers, rows


def verify(directory):
    result = subprocess.run([sys.executable, str(ROOT / "check_oeis.py"),
                             str(directory)], capture_output=True, text=True)
    if result.returncode:
        raise ValueError("check_oeis.py failed; README was not changed:\n"
                         + result.stdout + result.stderr)


def extent(value):
    return f"{value:.3e}" if value >= 1_000_000 else f"{value:,}"


def progress(directory, frontiers, rows):
    date = oeis_audit.data_date(str(directory))
    gap, lonely, aloof, equidistant, pairwise = (
        published(name) for name in
        ("gap", "lonely", "aloof", "equidistant", "pairwise"))
    lower, upper, span = (published(name) for name in
                          ("aloof-lower", "aloof-upper", "aloof-span"))
    if len(lower) != len(upper) or len(lower) != len(span):
        raise ValueError("aloof family snapshots have different lengths")
    sources = [
        ("gap, [A002386](https://oeis.org/A002386)", gap, gap[-1], "gap"),
        ("lonely, [A023186](https://oeis.org/A023186)", lonely, lonely[-1], "lonely"),
        ("aloof, [A031133](https://oeis.org/A031133)/[4](https://oeis.org/A031134)/[2](https://oeis.org/A031132)",
         [None] + lower, upper[-1], "aloof"),
        ("aloof, [A096265](https://oeis.org/A096265)", aloof, aloof[-1], "aloof"),
        ("equidistant, [A058867](https://oeis.org/A058867)",
         equidistant, equidistant[-1], "equidistant"),
        ("pairwise, [A087770](https://oeis.org/A087770)",
         pairwise, pairwise[-1], "pairwise"),
    ]
    lines = [
        "## Progress",
        "",
        "<!-- Generated by oeis_readme.py. Run `make oeis-readme` to refresh. -->",
        "",
        f"Snapshot of {date}, from the unseeded scan in `{directory.name}/`.",
        "Each family is complete through its own frontier in the last column.",
        "Published counts come from the committed snapshots in this directory.",
        "",
        "| family | published | published to | ours | shared terms | scan frontier |",
        "|--------|----------:|-------------:|-----:|-------------:|--------------:|",
    ]
    for label, pub, last, kind in sources:
        shared = min(len(pub), len(rows[kind]))
        lines.append(f"| {label} | {len(pub)} | {extent(last)} | "
                     f"{len(rows[kind])} | {shared} | {frontiers[kind]:,} |")
    lines.append(f"| balanced-lonely (proposed) | — | — | "
                 f"{len(rows['balanced'])} | — | {frontiers['lonely']:,} |")
    lines += [
        "",
        f"The aloof family has {len(lower)} published triples, corresponding to",
        f"A096265 indices 2–{len(lower) + 1}; the table counts its extra first term.",
        "",
        f"`python3 check_oeis.py {directory.name}` checks shared terms position by position,",
        "the aloof lower/upper/span family, and each record's bounding primes.",
        "The generated summary is written only after that check passes.",
        "",
    ]
    for kind, pub_count in (("gap", len(gap)), ("lonely", len(lonely)),
                            ("aloof", len(lower) + 1),
                            ("equidistant", len(equidistant)),
                            ("pairwise", len(pairwise))):
        extra = rows[kind][pub_count:]
        if extra:
            last = extra[-1]
            lines.append(f"- **{kind}:** {len(extra)} record(s) beyond the deepest "
                         f"committed OEIS sequence; latest {kind}({last[0]}) "
                         f"= {last[1]:,} (value {last[2]:,}).")
    if all(len(rows[kind]) <= count for kind, count in
           (("gap", len(gap)), ("lonely", len(lonely)),
            ("aloof", len(lower) + 1), ("equidistant", len(equidistant)),
            ("pairwise", len(pairwise)))):
        lines.append("- No scan records extend the deepest committed OEIS sequences yet.")
    lines += [
        "",
        "### What is being submitted",
        "",
        "The generated [`submit/edits.yaml`](submit/edits.yaml) is the live worklist.",
        "Run `make audit` to update it and this summary from the current scan.",
        "Record submission progress in [`submissions.txt`](submissions.txt).",
        "",
    ]
    return "\n".join(lines)


def covered(rows, date, run):
    n = {kind: len(records) for kind, records in rows.items()}
    specs = [
        ("A002386", "**gap**", "lower prime of a record gap", "—", "gap", "gap", 0),
        ("A000101", "gap", "upper prime of a record gap", "yes", "85", "gap", 0),
        ("A005250", "gap", "the record gap size", "yes", "85", "gap", 0),
        ("A053695", "gap", "differences between record gaps", "—", "84", "gap", -1),
        ("A023186", "**lonely**", "record min(gap below, gap above)", "—", "lonely", "lonely", 0),
        ("A023187", "lonely", "that distance", "—", "DATA 56", "lonely", 0),
        ("A096265", "**aloof**", "record nextprime(p) − prevprime(p)", "—", "aloof", "aloof", 0),
        ("A031133", "aloof", "lower neighbour, indexed one lower", "—", "aloof-lower", "aloof", -1),
        ("A031134", "aloof", "upper neighbour, indexed one lower", "—", "aloof-upper", "aloof", -1),
        ("A031132", "aloof", "the span", "—", "DATA 67", "aloof", -1),
        ("A058867", "**equidistant**", "record distance among balanced primes only", "—", "DATA 30", "equidistant", 0),
        ("A058868", "equidistant", "that distance", "—", "DATA 30", "equidistant", 0),
        ("A087770", "**pairwise**", "both gaps beat the previous term's", "—", "DATA 29", "pairwise", 0),
    ]
    lines = [
        "### Covered", "",
        "<!-- Generated by oeis_readme.py. Run `make oeis-readme` to refresh. -->",
        "",
        f"The `here` column counts records in `{run}/` at the {date} snapshot.",
        "Published counts below describe the OEIS entries at the time they were",
        "reviewed; the [snapshot table](#the-cached-b-files) lists committed b-files.",
        "", "| sequence | name here | what it holds | a-file | b-file | here |",
        "|----------|-----------|---------------|:------:|-------:|-----:|",
    ]
    for aid, name, desc, afile, bfile, kind, offset in specs:
        if bfile in {"gap", "lonely", "aloof", "aloof-lower", "aloof-upper"}:
            bfile = str(len(published(bfile)))
        lines.append(f"| [{aid}](https://oeis.org/{aid}) | {name} | {desc} | "
                     f"{afile} | {bfile} | {n[kind] + offset} |")
    lines.append(f"| not in OEIS | **balanced** | lonely records that are balanced "
                 f"primes | — | — | {n['balanced']} |")
    lines.append("")
    return "\n".join(lines)


def replace_section(text, start, end, replacement):
    first = text.find(start)
    last = text.find(end, first + len(start))
    if first < 0 or last < 0 or text.find(start, first + 1) >= 0:
        raise ValueError(f"expected exactly one section from {start!r} to {end!r}")
    return text[:first] + replacement.rstrip() + "\n\n" + text[last:]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", type=Path, default=ROOT / "fresh")
    args = ap.parse_args()
    directory = args.results.resolve()
    if not directory.is_dir():
        ap.error(f"results directory does not exist: {directory}")
    frontiers, rows = scan(directory)
    verify(directory)
    date = oeis_audit.data_date(str(directory))
    old = README.read_text()
    new = replace_section(old, "## Progress\n", PROGRESS_END,
                          progress(directory, frontiers, rows))
    new = replace_section(new, "### Covered\n", COVERED_END,
                          covered(rows, date, directory.name))
    if new != old:
        README.write_text(new)
        print(f"updated {README.relative_to(ROOT)}")
    else:
        print(f"{README.relative_to(ROOT)} is current")


if __name__ == "__main__":
    try:
        main()
    except ValueError as exc:
        sys.exit(str(exc))
